language: node_js
node_js: "10"
os: linux
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - 'export PATH=./node_modules/.bin:$PATH'
  - 'npm install -g typescript'
  - 'npm install -g vsce'
install:
  - 'npm install --ignore-scripts'
  - 'npm install'
  # https://github.com/travis-ci/travis-ci/issues/8813
  - 'rm -f ./node_modules/.bin/which'
  - 'npm run vscode:prepublish'
  - 'vsce package'
script:
  - 'npm test'
after_success:
  - if [[ $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_BRANCH == "master" ]]; then
    sonar-scanner;
    fi
deploy:
- provider: script
  script: vsce publish -p $VSCODE_TOKEN
  skip_cleanup: true
  on:
    repo: camel-tooling/vscode-yeoman
    branch: master
    tags: true
cache:
  directories:
    - "node_modules"
env: DISPLAY=:99
addons:
  sonarcloud:
    organization: "camel-tooling"
    branches:
      - master
